import { Footer, Header } from "@/components";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased h-[100svh] flex flex-col overflow-hidden`}>
        <Header />
        <div className="overflow-auto flex-grow flex flex-col">
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
